// Copies the compiled Vault ABI out of the Foundry build artifact so it is never
// hand-duplicated. Run via `npm run generate-abi` (also wired into predev/prebuild).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const artifactPath = join(here, "..", "..", "out", "CuratedLiquidityVault.sol", "CuratedLiquidityVault.json");
const outPath = join(here, "..", "src", "abis", "vault.ts");

if (!existsSync(artifactPath)) {
  console.error(
    `Foundry artifact not found at ${artifactPath}. Run "forge build" in the repo root first.`
  );
  process.exit(1);
}

const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
const abi = artifact.abi;

const contents =
  "// AUTO-GENERATED by scripts/generate-abi.mjs from out/CuratedLiquidityVault.sol/CuratedLiquidityVault.json\n" +
  "// Do not edit by hand — run `npm run generate-abi` after changing the Solidity contract.\n" +
  `export const vaultAbi = ${JSON.stringify(abi, null, 2)} as const;\n`;

writeFileSync(outPath, contents);
console.log(`Wrote ${abi.length} ABI entries to ${outPath}`);
